server:
  error:
    include-stacktrace: on_param
#spring:
#  datasource:
#      url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
#      username: rm94343
#      password: 280204
#      driverClassName: oracle.jdbc.OracleDriver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.OracleDialect
#        show_sql: true
#        format_sql: true
#        ddl-auto: create

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
